name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t startup2023/nestjs-rest-api .

      - name: Push Docker image
        run: docker push startup2023/nestjs-rest-api

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        run: ssh -i ${{ secrets.SSH_KEY }} ubuntu@34.243.23.159 "docker pull startup2023/nestjs-rest-api && docker run -d --restart always -p 80:3000 startup2023/nestjs-rest-api"
